WS2812_DRIVER = vendor
SERIAL_DRIVER = vendor
SPLIT_KEYBOARD = yes
SPLIT_USB_DETECT = yes
VIA_ENABLE=yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball

I2C_DRIVER_REQUIRED = yes